title: Sampo Sihvola
logo: /assets/img/profiili.png
description: Second-year IT student at Laurea University of Applied Sciences. Past work experience mainly from cultural & restaurant industries. Now looking for work in software testing & QA.
show_downloads: false
theme: jekyll-theme-minimal