plainwhite:
  name: Sampo Sihvola
  portfolio_image: /assets/img/profiili.png

  social_links:
    github: ssihvola

  navigation:
    - title: Portfolio
    url: "/README"
    - title: About
    url: "/about"

plugins:
  - jekyll-remote-theme
remote_theme: samarsault/plainwhite-jekyll